feat: add spacing tokens
cds-snc/gcds-tokens pull request #12
Opened 2022-03-24 00:39 UTC by melaniebmn

# Summary | Résumé

Tokens for:

- Spacing

2022-03-24 13:31 UTC, delisma requested changes

2022-03-24 13:31 UTC, delisma commented on tokens/spacing/base.json
> +    "space-1/2": {
We should be using a naming convention from 100-900 and then use the space-1/2 in the components tokens structure instead.

2022-03-25 20:46 UTC, delisma requested changes

2022-03-25 20:46 UTC, delisma commented on tokens/components/button/base.json
> +        "type": "button"
Type is still attached to the category not the component. In this case it's still linked to the color category.

2022-03-25 20:46 UTC, delisma commented on tokens/components/button/base.json
> +      "outline": {
We should aligned with the design decisions on buttons:
The solid variant would be the only variant included in the MVP for sake of simplicity and avoiding breaking change with the data model in the future (no outline or text only style at the moment)

2022-03-25 20:46 UTC, delisma commented on tokens/components/input/base.json
> +        "type": "input"
Type is still attached to the category not the component. In this case it's still linked to the color category.

2022-03-25 20:46 UTC, delisma commented on tokens/components/textarea/base.json
> +        "type": "textarea"
Type is still attached to the category not the component. In this case it's still linked to the color category.

2022-03-27 18:54 UTC, melaniebmn commented on tokens/components/button/base.json
> +      "outline": {
@delisma I removed all outline and text-only button tokens.

2022-03-28 20:35 UTC, melaniebmn commented on tokens/components/input/base.json
> +        "type": "input"
@delisma Type is updated to color.

2022-03-28 20:36 UTC, melaniebmn commented on tokens/components/textarea/base.json
> +        "type": "textarea"
@delisma Type is updated to color

2022-03-28 20:36 UTC, melaniebmn commented on tokens/components/button/base.json
> +        "type": "button"
@delisma Type is updated to color.

2022-03-28 20:36 UTC, melaniebmn commented
@delisma can you review the PR again pls? I updated it with your requested changes.

2022-04-21 18:00 UTC, closed without merging