New tokens for gcds-card
cds-snc/gcds-tokens pull request #127
Opened 2023-06-22 12:55 UTC by ethanWallace

# Summary | Résumé

New component tokens for `gcds-card` component.

Built for use with https://github.com/cds-snc/gcds-components/pull/183

2023-06-22 21:51 UTC, melaniebmn commented on tokens/components/card/tokens.json
> +      "value": "{border.width.sm.value} solid {color.grayscale.100.value}",
More of a design comment but: can we change this to use our default border token? `grayscale.100` does not pass the contrast ratio for borders and also deviates from what we defined as the default border.

2023-06-22 21:58 UTC, melaniebmn requested changes
Added a question about the border colour that we should address before merging.

2023-06-22 22:53 UTC, dylanzheng94 commented on tokens/components/card/tokens.json
> +      "value": "{border.width.sm.value} solid {color.grayscale.100.value}",
Updated the Figma component to use the default border token.

2023-06-26 18:02 UTC, melaniebmn commented on tokens/components/card/tokens.json
> +      "value": "{border.width.sm.value} solid {color.grayscale.100.value}",
Thank you!

2023-06-26 18:03 UTC, melaniebmn approved these changes
LGTM

2023-06-26 18:33 UTC, merged