feat: new tokens for link component
cds-snc/gcds-tokens pull request #173
Opened 2023-10-12 16:16 UTC by daine

# Summary | Résumé
Tokens for the new Link component

2023-10-12 22:07 UTC, melaniebmn commented on tokens/components/link/tokens.json
> +        "fontWeight": "{fontWeights.medium}",
Can you please change the `fontWeight` from `medium` to `regular` to match the design and general text style?

2023-10-12 22:08 UTC, melaniebmn commented on tokens/components/link/tokens.json
> +    "hover": {
Let's remove this token and use the global link hover token instead to not duplicate tokens and keep it a bit simpler :)

2023-10-12 22:11 UTC, melaniebmn commented on tokens/components/link/tokens.json
> +    "focus": {
Can you please add the other focus tokens for the link that are used for the focus style here:
https://github.com/cds-snc/gcds-components/pull/305/files#diff-7d564b71f770be346b3d550da929935fdb9ede207e882510069ef7d081902fb8R18

You can copy and paste them from the button tokens here:
https://github.com/cds-snc/gcds-tokens/blob/main/tokens/components/button/tokens.json#L137
https://github.com/cds-snc/gcds-tokens/blob/main/tokens/components/button/tokens.json#L3

2023-10-12 22:12 UTC, melaniebmn commented on tokens/components/link/tokens.json
> +          "fontSize": "80%"
And one more: can you check with Nick please if we will support smaller font sizes for this component? If yes, we can use `caption` for `lineHeight` and `fontSize`.

2023-10-12 22:13 UTC, melaniebmn requested changes
Added a few comments, let me know if you have any questions about these!

2023-10-13 21:45 UTC, daine commented
@melaniebmn verified with @nmakuch that:
- There would be no extra styling for active state for links
- `caption` size is available as a smaller font for links

2023-10-16 15:17 UTC, melaniebmn requested changes
Awesome, thanks for double-checking about the size and active state!

The tokens look good! Can you please update the package version to `1.8.0`? After that, the PR should be good to go.

2023-10-16 23:30 UTC, melaniebmn approved these changes
LGTM :)

2023-10-16 23:31 UTC, merged