chore: remove file header with date updates
cds-snc/gcds-tokens pull request #255
Opened 2024-04-23 20:28 UTC by melaniebmn

# Summary | Résumé

Oops just realized I forgot to push this after dev sync :D

Removing the file header to get rid of the "file changed" date for each token file

2024-04-23 23:23 UTC, daine requested changes
I found another way to keep the "Do not edit directly" line or even customize it. What do you think? LMK!

2024-04-23 23:23 UTC, daine commented on config.js
> +            showFileHeader: false,
Reading [this code on how it generates this](https://github.com/amzn/style-dictionary/blob/17f4cb2f30bd002dfd55d6ef8c5bee4138de8d64/lib/common/formatHelpers/fileHeader.js#L48), I found a way you can overwrite it! We can lose the date but still keep the "Do not edit file directly"

First set the header to a string var...
```javascript
const fileHeaderText = `Do not edit directly`;
```

Then apply this change:

```suggestion
            fileHeader: () => [fileHeaderText],
```

It will generate:
```
/**
 * Do not edit directly
 */
```

What do you think?

2024-04-24 00:20 UTC, melaniebmn commented on config.js
> +            showFileHeader: false,
@daine great idea, I updated the PR!

2024-04-24 00:35 UTC, daine commented on config.js
> +            showFileHeader: false,
Yay thank you!

2024-04-24 00:35 UTC, daine approved these changes
LGTM! Hopefully this causes us less pain <3

2024-04-24 13:07 UTC, ethanWallace approved these changes
LGTM

2024-04-24 15:39 UTC, merged