docs: add instructions on how to use design tokens
cds-snc/gcds-tokens pull request #279
Opened 2024-06-27 17:36 UTC by daine

# Summary | Résumé
Added instructions on how to use the GCDS Design Tokens
- https://github.com/cds-snc/design-gc-conception/issues/989

2024-07-12 00:30 UTC, daine commented
PR should be ready to review, we can update the instructions to add the FR translations for the update later

2024-07-15 23:00 UTC, melaniebmn commented on README.md
> +
Sorry very OCD (😆) but can we either remove this line break or add a line break between lines 41 and 42 as well?

2024-07-15 23:01 UTC, melaniebmn commented on README.md
> +@import 'path/to/node_modules/@cdssnc/gcds-tokens/build/web/css/tokens.css'
Do we need to  / should we include the package version here?

2024-07-15 23:03 UTC, melaniebmn commented on README.md
> +Choose to only include GCDS component tokens if you are planning on only using component-specific tokens. Add GCDS component-specific tokens to your CSS by importing the CSS file for a specific compo
`<gcds-button>` needs to be changed to ``gcds-button`` to render properly in the readme. We normally only add the <> in documents to signal to translation that this is code and doesn't need to be translated.

2024-07-15 23:08 UTC, melaniebmn commented on README.md
> +Choose to only include GCDS component tokens if you are planning on only using component-specific tokens. Add GCDS component-specific tokens to your CSS by importing the CSS file for a specific compo
`<gcds-button>` and `<button.css>` need to be changed to render properly in the readme. We normally only add the <> in documents to signal to the translation team that this is code and doesn't need to be translated.

```suggestion
Choose to only include GCDS component tokens if you are planning on only using component-specific tokens. Add GCDS component-specific tokens to your CSS by importing the CSS file for a specific component. For example, add the component tokens for the `gcds-button` component by importing the `button.css` file:
```

2024-07-15 23:08 UTC, melaniebmn commented on README.md
> +Choose to include all GCDS tokens if you are planning on using the component, global and base tokens. Add all GCDS tokens to your CSS by importing the <tokens.css> file:
```suggestion
Choose to include all GCDS tokens if you are planning on using the component, global and base tokens. Add all GCDS tokens to your CSS by importing the `tokens.css` file:
```

2024-07-15 23:09 UTC, melaniebmn commented on README.md
> +Add all GCDS tokens in your SCSS by importing the <tokens.scss> file:
```suggestion
Add all GCDS tokens in your SCSS by importing the `tokens.scss` file:
```

2024-07-15 23:09 UTC, melaniebmn commented on README.md
> +Add the component tokens in your SCSS for the <gcds-button> component by importing the <button.scss> file:
```suggestion
Add the component tokens in your SCSS for the <gcds-button> component by importing the `button.scss` file:
```

2024-07-15 23:10 UTC, melaniebmn commented on README.md
> +Repeat the above step for each component-specific CSS or SCSS file you want to include. Or include all component-specific tokens to your CSS by importing the <components.css> file:
```suggestion
Repeat the above step for each component-specific CSS or SCSS file you want to include. Or include all component-specific tokens to your CSS by importing the `components.css` file:
```

2024-07-15 23:11 UTC, melaniebmn commented on README.md
> +Add all component tokens in your SCSS by importing the <components.scss> file:
```suggestion
Add all component tokens in your SCSS by importing the `components.scss` file:
```

2024-07-15 23:11 UTC, melaniebmn commented on README.md
> +Choose to only include the GCDS global and base tokens if you don’t need component-specific tokens. Add GCDS global and base tokens to your CSS by importing the <base.css> and <global.css> files:
```suggestion
Choose to only include the GCDS global and base tokens if you don’t need component-specific tokens. Add GCDS global and base tokens to your CSS by importing the `base.css` and `global.css` files:
```

2024-07-15 23:12 UTC, melaniebmn commented on README.md
> +Add the GCDS global and base tokens to your SCSS by importing the <base.scss> and <global.scss> files:
```suggestion
Add the GCDS global and base tokens to your SCSS by importing the `base.scss` and `global.scss` files:
```

2024-07-15 23:12 UTC, melaniebmn requested changes
Added some formatting suggestions :)

2024-07-16 16:54 UTC, daine commented on README.md
> +Choose to only include GCDS component tokens if you are planning on only using component-specific tokens. Add GCDS component-specific tokens to your CSS by importing the CSS file for a specific compo
I didn't know about that and never did it that way, now I do! Thanks for these commit suggestions, makes my job way easier!

2024-07-16 20:49 UTC, melaniebmn approved these changes
LGTM

2024-07-16 23:46 UTC, merged