chore: update style dictionary
cds-snc/gcds-tokens pull request #339
Opened 2024-10-29 21:53 UTC by melaniebmn

# Summary | Résumé

Updating Style Dictionary from version `3.9.2` to version `4.1.4`. Style Dictionary introduced a lot of breaking changes with this major version release which required some updates to our config file.

To prepare for the rework of our typography tokens, which will happen soon, I took the opportunity to split them into separate files for easier maintenance and also cleaned up the code for the font sizes and line height calculations.

With this update, I was also able to remove the weird `.css` and `.scss` files that were being generated which we didn't use anywhere. In addition, we do not need to have the custom file header text anymore which prevented the timestamp from being generated for each build file. Style Dictionary finally doesn't include a timestamp in the file header output by default anymore, it is now an opt-in setting.

Apologies for the amount of changed files - the removal of our custom file header meant that we are now going back to the default Style Dictionary header which included some extra text.

2024-10-29 22:39 UTC, daine commented on tokens/components/icon/tokens.js
> +  size: createPropertiesObject(fontSizeKeys, 'fontSizes'),
Nice! So much cleaner!

2024-10-29 23:18 UTC, daine requested changes
This is amazing! I have a few comments.

I also haven't tested it yet in comparison to what we currently have -- is that something you have tested, and what is the process you use to test it? I can only think if doing a diff on the build files and I'm not sure if that's efficient!

2024-10-29 23:18 UTC, daine commented on tokens/global/typography/fontSizes.js
> +};
Just wondering if we can also refactor this? I was thinking of having it in a setting like:

```js
const multiplier = {
  h1: 6,
  h2: 5,
  h3: 4,
  h4: 3,
  h5: 2,
  h6: 1,
};

/**
 * Generates an object containing font sizes for various headings and text elements.
 *
 * @param {number} baseScaleValue - The base scale value used for calculating font sizes.
 * @param {Object.<string, number>} multiplier - An object mapping heading names to their corresponding scale multipliers.
 * @returns {Object.<string, any>} An object containing the generated font sizes.
 */
function getFontSizes(baseScaleValue: number, multiplier: { [key: string]: number }) {
  const fontSizes: { [key: string]: any } = {
    caption: createFontSize('caption', false, 1 / baseScaleValue),
    captionMobile: createFontSize('caption', true, 1 / baseScaleValue),
    text: createFontSize('text'),
    textMobile: createFontSize('text', true),
  };

  Object.keys(multiplier).forEach(heading => {
    fontSizes[heading] = createFontSize(heading, false, baseScaleValue ** multiplier[heading]);
    fontSizes[`${heading}Mobile`] = createFontSize(heading, true, baseScaleValue ** multiplier[heading]);
  });

  return fontSizes;
}

const fontSizes = generateFontSizes(base.scale.value, multiplier);
```

What I like most about this presentation is that you can modify the multiplier values quicker without having to read the actual code that generates the sizes

2024-10-29 23:18 UTC, daine commented on tokens/global/typography/lineHeights.js
> +  const octave = 6;
Is this always a constant? Are there any benefits to having this passed in as a parameter with a default value?

2024-10-29 23:18 UTC, daine commented on tokens/global/typography/lineHeights.js
> +*/
I love this!!! Could we switch to JSDoc format?
```suggestion
/**
 * Calculates the line height as a percentage of the font size value.
 * Get fontSize value, divided away from the base font scaling
 * LineHeight has no units, its relative
 * Find out how many baseline octaves are required to fit the fontSize. Add one octave for a bit more spacing
 * @param {string} fontSize - The font size value as a string.
 * @returns {number} The calculated line height as a percentage of the font size value.
 */
```

Also just trying to come up with a better description for the octave computation, but I can't think of a better one ATM

2024-10-29 23:18 UTC, daine commented on tokens/global/typography/lineHeights.js
> +  h6Mobile: createLineHeight('h6Mobile', fontSizes.h6Mobile.value),
I have the same suggestion for this (see fontSizes)

2024-10-30 15:42 UTC, melaniebmn commented on tokens/components/icon/tokens.js
> +  acc[key] = {
Good question if it is applicable here. I looked at a few other spots in our tokens where we create tokens for the width and we seem to be using the type "sizing" for those so I will switch it over to use "sizing" instead of "dimensions".

2024-10-30 16:37 UTC, melaniebmn commented on tokens/global/typography/fontSizes.js
> +};
Good idea! I added it in a slightly modified version to improve readability a little bit more :)

2024-10-30 17:16 UTC, melaniebmn commented on tokens/global/typography/lineHeights.js
> +  const octave = 6;
I believe it will always be a constant. The person who wrote this did a lot of manual work in Figma to figure out the octave value. I'm not sure we would need to change it at some point.

2024-10-30 17:57 UTC, melaniebmn commented
> This is amazing! I have a few comments.
> 
> I also haven't tested it yet in comparison to what we currently have -- is that something you have tested, and what is the process you use to test it? I can only think if doing a diff on the build files and I'm not sure if that's efficient!

@daine, I have tested it a lot by checking the diff on the build files to ensure everything compiles to the same values. I'm unsure if there is any other testing we could do, but let me know if you have any ideas!

2024-10-30 18:13 UTC, ethanWallace approved these changes
LGTM!

2024-11-05 01:18 UTC, melaniebmn commented
Closing this PR in favor of [#344](https://github.com/cds-snc/gcds-tokens/pull/344).

2024-11-05 01:18 UTC, closed without merging