chore: update style dictionary
cds-snc/gcds-tokens pull request #344
Opened 2024-11-05 01:18 UTC by melaniebmn

# Summary | Résumé

Updating Style Dictionary from version 3.9.2 to version 4.1.4. Style Dictionary introduced a lot of breaking changes with this major version release which required some updates to our config file.

To prepare for the rework of our typography tokens, which will happen soon, I took the opportunity to split them into separate files for easier maintenance and also cleaned up the code for the font sizes and line height calculations.

With this update, I was also able to remove the weird .css and .scss files that were being generated which we didn't use anywhere. In addition, we do not need to have the custom file header text anymore which prevented the timestamp from being generated for each build file. Style Dictionary finally doesn't include a timestamp in the file header output by default anymore, it is now an opt-in setting.

Apologies for the giant PR and amount of changed files - the removal of our custom file header meant that we are now going back to the default Style Dictionary header which included some extra text.

2024-11-05 03:51 UTC, daine requested changes
Just more thing I noticed, but it looks great!

2024-11-05 03:51 UTC, daine commented on tokens/components/icon/tokens.js
> +  size: createPropertiesObject(fontSizeKeys, 'fontSizes'),
chef's kiss - i love deleting code

2024-11-05 03:51 UTC, daine commented on tokens/global/typography/lineHeights.js
> +const octave = 6;
Just curious here - who is the person who defined the octave (the person who did the manual work in figma), and could we have that referenced here if possible for historical purposes?

2024-11-05 03:51 UTC, daine commented on tokens/global/typography/lineHeights.js
> +  const fontSizeValue = parseFloat(fontSize) / base.fontSize.value;
This function, if the `fontSize` is set to `base.fontSize.value` returns the same value as
```
base.lineHeight.value * 100
```

but we can simply skip all the other computation and just return the value if we're computing the line height for the base font size like this:

```suggestion
  const calculateLineHeight = (fontSize) => {
  if( fontSize === base.fontSize.value ) {
    return base.lineHeight.value * 100
  }
  const fontSizeValue = parseFloat(fontSize) / base.fontSize.value;
```

2024-11-05 03:51 UTC, daine commented on tokens/global/typography/lineHeights.js
> +  },
Could we also change this to move the computation in the function? See comment above!

2024-11-20 00:36 UTC, melaniebmn commented on tokens/global/typography/lineHeights.js
> +const octave = 6;
It was Phil when he was briefly on our team. I will rewrite this part when I implement the new typography and spacing so we can replace the octave.

2024-11-20 00:36 UTC, melaniebmn commented on tokens/components/icon/tokens.js
> +  size: createPropertiesObject(fontSizeKeys, 'fontSizes'),
Me too :)

2024-11-20 00:38 UTC, melaniebmn commented on tokens/global/typography/lineHeights.js
> +  const fontSizeValue = parseFloat(fontSize) / base.fontSize.value;
I will rewrite the line height calculation to implement the new typography. Would you be okay with leaving it as is for now?

2024-11-20 00:57 UTC, daine commented on tokens/global/typography/lineHeights.js
> +  const fontSizeValue = parseFloat(fontSize) / base.fontSize.value;
Yes sounds good to me!

2024-11-20 00:58 UTC, daine approved these changes
LGTM!

2024-11-20 01:06 UTC, merged