chore: add french translations to the changelog
cds-snc/gcds-tokens pull request #349
Opened 2024-12-06 00:13 UTC by daine

# Summary | Résumé

2024-12-09 14:52 UTC, SmartMouthWords requested changes
Lines 838, 947, and 948 need French, as follows: 

- 838: "Version publiée le : 2024-09-13 
- 947: "Refactorisation de code"
- 948: "supprimer les unités de style redondantes après la réécriture CSS (#230) (d819ecf)"

2024-12-09 21:45 UTC, SmartMouthWords commented
Okay, i found 3 lines that had English text. If all the text is now in French, should be gtg

2024-12-10 14:35 UTC, SmartMouthWords commented on CHANGELOG.md
> +    old-tokens["`Ancienne des unités de style`"] ~~~ new-tokens["`Nouvelle unité de style`"]
French would be: 
"Anciennes unités de style" and "Nouvelles unités de style"

2024-12-10 14:36 UTC, SmartMouthWords commented on CHANGELOG.md
> +* revenir sur la mise à jour des unités de style de l’indicateur d’étape jusqu'à ce que l’indicateur d’étape soit prêt pour la publication ([#278](https://github.com/cds-snc/gcds-tokens/issues/278))
@daine Yes, "récupérer" is a better fit.

2024-12-10 14:40 UTC, SmartMouthWords commented on CHANGELOG.md
> +* remove tokens redundant after CSS rewrite ([#230](https://github.com/cds-snc/gcds-tokens/issues/230)) ([d819ecf](https://github.com/cds-snc/gcds-tokens/commit/d819ecf92d068bb8f675b1f9687f246e8f6a55
@daine This is the line and the one that precedes it where there's English text. it can be replaced with the French I provided in the first comment I made.

2024-12-10 14:52 UTC, SmartMouthWords commented
@daine Found something I missed. It's only an issue in this repo. Every instance of "jeton" needs to be replaced with "unité de style" and "jetons" with "unités de style".

2024-12-10 14:57 UTC, SmartMouthWords commented
> @daine Found something I missed. It's only an issue in this repo. Every instance of "jeton" needs to be replaced with "unité de style" and "jetons" with "unités de style".
More details: 
- "des jetons" becomes "des unités de style"
- "du jeton" becomes "de l'unité de style" 
- "d'un jeton" becomes "d'une unité de style" 
- "nouveaux jetons" becomes "nouvelles unités de style" 
- "de jeton" becomes "de l'unité de style"
- "jetons globaux" becomes "unités de styles globales"

2024-12-10 17:17 UTC, daine commented on CHANGELOG.md
> +    old-tokens["`Ancienne des unités de style`"] ~~~ new-tokens["`Nouvelle unité de style`"]
```suggestion
    old-tokens["`Anciennes unités de style`"] ~~~ new-tokens["`Nouvelles unités de style`"]
```

2024-12-10 20:24 UTC, SmartMouthWords commented on CHANGELOG.md
> +\* :no_entry_sign: les valeurs des unités de style en rouge ont changé et sont désormais obsolètes. Les anciennes unités de style ont été affectées avec de nouvelles valeurs. [Contactez-nous](https:/
```suggestion
\* :no_entry_sign: les valeurs des unités de style en rouge ont changé et sont désormais obsolètes. Les anciennes unités de style ont été affectées avec de nouvelles valeurs. [Contactez-nous](https://design-system.alpha.canada.ca/en/contact/) si vous utilisez ces unités de style.
```

2024-12-10 20:25 UTC, SmartMouthWords approved these changes

2024-12-10 20:48 UTC, ethanWallace approved these changes
LGTM

2024-12-10 20:54 UTC, merged