Commented and introduced octaves to calculateLineHeight.
cds-snc/gcds-tokens pull request #67
Opened 2023-01-10 20:56 UTC by amazingphilippe

# Summary | Résumé

- Added comments to calculateLineHeight to understand what is happening
- Made the code a bit more readable. I think?
- Added support for octaves. This allows us to fine tune our typographic rhythm

This prioritizes the reader a bit more than a strict baseline grid. 

An example before octaves. All lines are multiples of 26. H3 and H4 looks super spaced out, while h5 and h6 lines are jammed to each other

![image](https://user-images.githubusercontent.com/5230720/211659523-406a60e0-68c4-4b9d-ac24-fcbe050c71f3.png)

An example with 2 octaves. All lines are a multiple of 13 (26/2). H3 and H4 are a bit better. H2 H5 and H6 are still jammed together

![image](https://user-images.githubusercontent.com/5230720/211658560-89c3105e-4cf1-47ac-9fc0-8852fd74b133.png)

Maybe its also about tuning the fontSize scale

2023-01-11 16:26 UTC, amazingphilippe commented
I did a bit more digging to understand better why some scales look more uniform than others. So I made graphs! We can see how some scales produce more sudden variation. By pure chance, I stumbled upon a pretty smooth combination at a baseline of 28 with 7 octaves:


![image](https://user-images.githubusercontent.com/5230720/211860919-869217e6-e717-4fbd-bd3e-6e2290fb5cfd.png)

2023-01-11 16:40 UTC, amazingphilippe commented
24 baseline with 6 octaves also creates something nice. Also would produce better spacing tokens, as seen in #66

2023-01-12 16:56 UTC, melaniebmn commented on tokens/base/typography/base.js
> +  paragraph: {
Text is supposed to represent the paragraph line height or do you think we need two different line heights available for text?

2023-01-12 16:56 UTC, melaniebmn requested changes
One small comment but otherwise looks good

2023-01-12 18:11 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +  paragraph: {
Yes! This is what[ WCAG Text spacing](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html) recommends for paragraphs: 150% the font size at least. Actually I think this should be fontSize * 1.5

Good catch!

2023-01-12 18:17 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +  paragraph: {
I actually set it directly to 150%. I figured we did not need any fancy math

2023-01-12 19:35 UTC, melaniebmn commented on build/figma/figma.tokens.json
> +      "paragraph": {
Sorry, my comment earlier wasn't very clear. Do we need to create a new paragraph token or can we set the text line height token to 150% instead since that is the token that is supposed to be used for all text?

2023-01-12 19:36 UTC, melaniebmn commented on tokens/base/typography/base.js
> +  paragraph: {
Sorry, my comment earlier wasn't very clear. Do we need to create a new paragraph token to have two options available for text or can we set the text line height token to 150% instead since that is the token that is supposed to be used for all text?

2023-01-12 19:37 UTC, melaniebmn requested changes
One small change, explained my comment from earlier a little bit better.

2023-01-12 20:10 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +  paragraph: {
No we need both! the "text" line height is useful for buttons or shorter lengths of text. A "paragraph" line height is just for composing longer paragraphs!

2023-01-12 21:00 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +  paragraph: {
BTS: Not including paragraph line height for now. Keeping it simple

2023-01-12 21:00 UTC, melaniebmn approved these changes
LGTM

2023-01-12 21:06 UTC, melaniebmn approved these changes
LGTM

2023-01-12 21:06 UTC, merged