Update token components
cds-snc/gcds-tokens pull request #73
Opened 2023-01-20 16:57 UTC by ethanWallace

# Summary | Résumé

Update components to use tokens for all typography, spacing, and colours for:

Button
Checkbox
Date modified
Fieldset
Footer
Header
Language toggle
Pagination
Radio button
Signature

2023-01-23 23:14 UTC, melaniebmn commented on tokens/components/button/base.json
> +          "type": "fontSize"
Small typo here, it needs to be "fontSizes" in order to work properly in Figma.

2023-01-23 23:16 UTC, melaniebmn commented on tokens/components/checkbox/base.json
> +      "width": {
When I did the tokens, I wasn't sure about combing these values into one token to make sure they are the same. What do you think?

2023-01-23 23:20 UTC, melaniebmn commented on tokens/components/radio/base.json
> +      "width": {
Same comment about maybe combing them into one token? Let's discuss maybe.

2023-01-23 23:26 UTC, melaniebmn commented on tokens/components/date-modified/base.json
> +      "left": {
Potentially change these tokens to be for `margin`, instead of `margin-top` and `margin-left` - see comment about multi-language in components PR.

2023-01-23 23:27 UTC, melaniebmn commented on tokens/components/fieldset/base.json
> +        "bottom": {
Same comment about multi-language.

2023-01-23 23:27 UTC, melaniebmn commented on tokens/components/footer/base.json
> +        "bottom": {
Same comment about multi-language.

2023-01-23 23:27 UTC, melaniebmn commented on tokens/components/footer/base.json
> +          "marginBottom": {
Same comment about multi-language.

2023-01-23 23:28 UTC, melaniebmn commented on tokens/components/footer/base.json
> +        "marginRight": {
Same comment about multi-language.

2023-01-23 23:28 UTC, melaniebmn commented on tokens/components/footer/base.json
> +          "bottom": {
Same comment about multi-language.

2023-01-23 23:29 UTC, melaniebmn commented on tokens/components/header/base.json
> +        "top": {
Same comment about multi-language.

2023-01-23 23:29 UTC, melaniebmn commented on tokens/components/header/base.json
> +        "bottom": {
Same comment about multi-language.

2023-01-23 23:31 UTC, melaniebmn commented on tokens/components/pagination/base.json
> +            "top": {
Same comment about multi-language.

2023-01-23 23:31 UTC, melaniebmn commented on tokens/components/pagination/base.json
> +          "bottom": {
Same comment about multi-language.

2023-01-23 23:32 UTC, melaniebmn commented on tokens/components/signature/base.json
> +      "bottom": {
Same comment about multi-language.

2023-01-23 23:32 UTC, melaniebmn commented on tokens/components/signature/base.json
> +        "bottom": {
Same comment about multi-language.

2023-01-23 23:32 UTC, melaniebmn commented on tokens/components/signature/base.json
> +        "bottom": {
Same comment about multi-language, same with margin top right below.

2023-01-23 23:33 UTC, melaniebmn requested changes
Overall the tokens look great! I did add comments on lines where the multi-language styling for margin and padding can be improved and thought, this could be a good opportunity to do that.

2023-01-24 13:44 UTC, ethanWallace commented on tokens/components/radio/base.json
> +      "width": {
Makes sense to me to do that since the height and width should always be the same value. I will make the change

2023-01-24 19:37 UTC, melaniebmn commented on tokens/components/button/base.json
> +      "value": "1rem .75rem",
Can you use spacing tokens for this?
We have a spacing token for `1.125rem` and one for `0.75rem`.

2023-01-24 19:41 UTC, melaniebmn commented on tokens/components/checkbox/base.json
> +        }
Can you adjust the line-height to use the caption line-height, please?
Just so we stay consistent with our own guidance.

2023-01-24 19:49 UTC, melaniebmn requested changes
2 small requests, otherwise it looks good.

2023-01-24 21:21 UTC, melaniebmn approved these changes
LGTM

2023-01-25 12:55 UTC, merged