Adding typography styles and transform to process as css/scss font prop.
cds-snc/gcds-tokens pull request #74
Opened 2023-01-23 19:39 UTC by amazingphilippe

# Summary | Résumé

We have tokens for individual typography attributes, but we can do a bit more for Figma by creating text styles containing all attributes needed to compose an h1, h2, label, etc. 

These are a bit more opinion based, but they also are optional and don't interfere with individual props. They also provide a useful shortcut to compose typography.

For css, we can also compose a [font shorthand declaration](https://developer.mozilla.org/en-US/docs/Web/CSS/font). Which could be equally useful as utilities to apply everything at once.

2023-01-23 19:45 UTC, amazingphilippe commented on config.js
> +        'color/css',
[Can't mix transform groups and custom transforms](https://github.com/amzn/style-dictionary/issues/813), so I just looked in here to see what was included in the [preset transform groups](https://github.com/amzn/style-dictionary/blob/b20f3a57f4a5dd853e19ba5c8d144b6473c67d6d/lib/common/transformGroups.js#L66-L95)

2023-01-23 19:46 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +    hint: {
We use "hint" more often than "caption". But should we make a specific one named "caption" ?

2023-01-24 17:48 UTC, melaniebmn commented on tokens/base/typography/base.js
> +  typography: {
Can you remove this line to remove the double typography listing in the variable names?

2023-01-24 17:49 UTC, melaniebmn commented on tokens/base/typography/base.js
> +        fontWeight: '{fontWeights.medium}',
I believe the headings are all supposed to use a bold font weight.

2023-01-24 17:50 UTC, melaniebmn commented on tokens/base/typography/base.js
> +    hint: {
I would say let's stick with `caption` to stay consistent with the rest of our tokens.

2023-01-24 17:52 UTC, melaniebmn commented on tokens/base/typography/base.js
> +    paragraph: {
I know we briefly talked about this before, but can we name this something else rather than `paragraph` to avoid confusion? Maybe `textLineHeightLarge` or `textLongParagraphs`? I can't think of a good name right now, but I think having a `text` and a `paragraph` style without any further explanation in the name would be confusing.

2023-01-24 17:55 UTC, melaniebmn commented on tokens/base/typography/base.js
> +const typography = {
Instead of naming this `typography`, how about using `font` to stay consistent with the CSS property it represents in the code?

In that case, the variable could look like this:
`--gcds-font-h1`

Instead of:
`--gcds-typography-typography-h1`

2023-01-24 17:58 UTC, melaniebmn commented on tokens/base/typography/base.js
> +        category: 'typography',
Just for my own understanding: We need to add a `type: typography` and an attribute `category: typography` to make the transform work properly, right?

2023-01-24 17:59 UTC, melaniebmn requested changes
Great idea to add these typography styles! I added some questions and suggestions.

2023-01-24 18:26 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +    paragraph: {
Maybe through a comment? I can call it `longText` too. That would be closer to `text`

2023-01-24 18:27 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +const typography = {
It maybe because of the Figma tokens plugin. I'll check if I can change it. and make it work somehow. I agree it would make more sense in the CSS universe.

2023-01-24 18:27 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +        category: 'typography',
Yeah, I had trouble reaching the `type` from the transform function.

2023-01-24 19:10 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +const typography = {
(It worked) turns out the `type: typography` is important, but the label can be font. 🎉

2023-01-24 19:17 UTC, melaniebmn commented on tokens/base/typography/base.js
> +    paragraph: {
Yes, I think `longText` might make its function a bit more obvious.

2023-01-24 19:18 UTC, melaniebmn commented on tokens/base/typography/base.js
> +const typography = {
Yay awesome, thank you for checking!

2023-01-24 19:20 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +        category: 'typography',
Not 100% sure, but I think un-nesting the double `typography` and/or renaming to `font` might have fixed this. So I removed the whole attribute key and updated the transform. The output is the same!

2023-01-24 19:21 UTC, amazingphilippe commented on build/figma/figma.tokens.json
> +        "value": 1.125
I removed `type` here because it was nonsense in Figma, and doesn't impact css package.

2023-01-24 19:24 UTC, amazingphilippe commented on tokens/base/typography/base.js
> -    type: 'typography',
I removed `type` here because it was nonsense in Figma, and doesn't impact css package. See `figma.tokens.json` to see the effect.

2023-01-24 19:25 UTC, amazingphilippe commented on build/figma/figma.tokens.json
> +      },
A `type: typography` needs to contain at least these 4 value to make any sense in Figma.

2023-01-24 19:27 UTC, melaniebmn commented on tokens/base/typography/base.js
> +  longText: {
Sorry for being nit-picky, but can we use `textLong` instead of `longText`? If we use `textLong`, the two text variables will both be displayed right below each other which makes it easier to see that there are two text options.

2023-01-24 19:31 UTC, melaniebmn requested changes
One small nit-picky request, but otherwise looks great.

2023-01-24 19:48 UTC, amazingphilippe commented on tokens/base/typography/base.js
> +  longText: {
Good idea!

2023-01-24 19:57 UTC, melaniebmn submitted a review, later dismissed
LGTM

2023-01-24 20:30 UTC, melaniebmn approved these changes
LGTM

2023-01-24 20:46 UTC, merged